//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LibSassHost.Resources
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	internal class Strings
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"LibSassHost.Resources.Strings",
#if NET20 || NET30 || NET35 || NET40
				typeof(Strings).Assembly
#else
				typeof(Strings).GetTypeInfo().Assembly
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		internal static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		internal static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "The parameter `{0}` must be a non-empty string."
		/// </summary>
		internal static string Common_ArgumentIsEmpty
		{
			get { return GetString("Common_ArgumentIsEmpty"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The parameter '{0}' must be a non-nullable."
		/// </summary>
		internal static string Common_ArgumentIsNull
		{
			get { return GetString("Common_ArgumentIsNull"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "File '{0}' not exist."
		/// </summary>
		internal static string Common_FileNotExist
		{
			get { return GetString("Common_FileNotExist"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "See the original error message: “{0}”."
		/// </summary>
		internal static string Common_SeeOriginalErrorMessage
		{
			get { return GetString("Common_SeeOriginalErrorMessage"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Failed to add the '{0}' directory to the search path used to locate DLLs for the application."
		/// </summary>
		internal static string Compiler_AddingDirectoryToDllSearchPathFailed
		{
			get { return GetString("Compiler_AddingDirectoryToDllSearchPathFailed"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Most likely it happened, because the '{0}' assembly or one of its dependencies was not found."
		/// </summary>
		internal static string Compiler_AssemblyNotFound
		{
			get { return GetString("Compiler_AssemblyNotFound"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "You can build the '{0}' assembly for the current processor architecture by using following..."
		/// </summary>
		internal static string Compiler_BuildNativeAssemblyForCurrentProcessorArchitecture
		{
			get { return GetString("Compiler_BuildNativeAssemblyForCurrentProcessorArchitecture"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "{0} packages do not support installation under Mono, but you can to install the native assembly..."
		/// </summary>
		internal static string Compiler_ManualInstallationUnderMonoRequired
		{
			get { return GetString("Compiler_ManualInstallationUnderMonoRequired"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "There is no {0} package for the {1} processor architecture."
		/// </summary>
		internal static string Compiler_NoNuGetPackageForProcessorArchitecture
		{
			get { return GetString("Compiler_NoNuGetPackageForProcessorArchitecture"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Try to install the {0} package via NuGet."
		/// </summary>
		internal static string Compiler_NuGetPackageInstallationRequired
		{
			get { return GetString("Compiler_NuGetPackageInstallationRequired"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Your operating system is not supported by the engine."
		/// </summary>
		internal static string Compiler_OperatingSystemNotSupported
		{
			get { return GetString("Compiler_OperatingSystemNotSupported"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "During loading of Sass compiler error has occurred."
		/// </summary>
		internal static string Compiler_SassCompilerNotLoaded
		{
			get { return GetString("Compiler_SassCompilerNotLoaded"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Column number"
		/// </summary>
		internal static string ErrorDetails_ColumnNumber
		{
			get { return GetString("ErrorDetails_ColumnNumber"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Description"
		/// </summary>
		internal static string ErrorDetails_Description
		{
			get { return GetString("ErrorDetails_Description"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Error code"
		/// </summary>
		internal static string ErrorDetails_ErrorCode
		{
			get { return GetString("ErrorDetails_ErrorCode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "File"
		/// </summary>
		internal static string ErrorDetails_File
		{
			get { return GetString("ErrorDetails_File"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Line number"
		/// </summary>
		internal static string ErrorDetails_LineNumber
		{
			get { return GetString("ErrorDetails_LineNumber"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Message"
		/// </summary>
		internal static string ErrorDetails_Message
		{
			get { return GetString("ErrorDetails_Message"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Source fragment"
		/// </summary>
		internal static string ErrorDetails_SourceFragment
		{
			get { return GetString("ErrorDetails_SourceFragment"); }
		}

		private static string GetString(string name)
		{
			string value = ResourceManager.GetString(name, _resourceCulture);

			return value;
		}
	}
}